### ISSUE TITLE
Conflict with the original PLM

### ISSUE THREAD

**Issue by anviz-github** [OmniaGit/odooplm#49]
Conflicts with the original plm. When start new revision of BOM is performed on an ECO in the original PLM, bom materials will be added and removed inexplicably.
Thank you!
Here is the screenshots:
<img width="1440" alt="Screen Shot 2020-03-04 at 6 10 43 PM" src="https://user-images.githubusercontent.com/54052406/75868798-94c54f00-5e43-11ea-8a61-fa74466b4814.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 6 10 43 PM" src="https://user-images.githubusercontent.com/54052406/75871888-351d7280-5e48-11ea-916d-f5b8bc9002bd.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 6 42 20 PM" src="https://user-images.githubusercontent.com/54052406/75871899-38b0f980-5e48-11ea-8819-96ed4035d7ed.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 6 42 27 PM" src="https://user-images.githubusercontent.com/54052406/75871907-39e22680-5e48-11ea-8dce-0fb64af8cc74.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 6 42 33 PM" src="https://user-images.githubusercontent.com/54052406/75871911-3b135380-5e48-11ea-89d4-4b86edca9f26.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 6 44 17 PM" src="https://user-images.githubusercontent.com/54052406/75871914-3babea00-5e48-11ea-8c6c-4dbba1a68ab7.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 6 44 21 PM" src="https://user-images.githubusercontent.com/54052406/75871920-3cdd1700-5e48-11ea-8997-58dd0afac350.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 6 44 23 PM" src="https://user-images.githubusercontent.com/54052406/75871923-3ea6da80-5e48-11ea-8595-0ffc2d1591f5.png">
<img width="1440" alt="Screen Shot 2020-03-04 at 6 44 30 PM" src="https://user-images.githubusercontent.com/54052406/75871927-3f3f7100-5e48-11ea-8ace-c15b77d6d43e.png">

**Comment by OmniaGit** [comment]
Dear,
thanks for your report.
we check the issue and we found that the problem is related to the odoo module itself.
for this we have opened an issue to the odoo github account and you can follow it at
https://github.com/odoo/odoo/issues/47002

the problem you are facing is due to the configuration of our plm module.
if you save your bom from the cad we save more than one line for the same parts
es:
parent
->child qty 1
->child qty1
..
..

if you wont to avoid this behaviour you need ot install the option that enable the engineering bom.
in this way you can have the engineering_bom and the normal bom
the normal bom can be created form the enginering bom with a special command and is summarised.

otherwise the v13 have a new module that allows you to upload the normal bom as summarized

regards
Matteo

**Comment by anviz-github** [comment]
thank you
