### ISSUE TITLE
After installed odooplm，when create a BOM ECO an exception occurs

### ISSUE THREAD

**Issue by anviz-github** [OmniaGit/odooplm#50]
https://youtu.be/WoKlmaS3yCU

**Comment by OmniaGit** [comment]
Dear Anviz,
We check several time the issue you report but we are not able to reproduce it.

The algorithm that is in charged of adding part in the bom eco make a compare only for the following attributes:

>   (line.product_uom_id, line.product_qty, line.operation_id) != (old_line.product_uom_id, old_line.product_qty, old_line.operation_id)

Please have a check of all the bom involved to see if there is any difference.
Be aware that odoo make a new bom for each eco, and put the new one in active=False mode.

In order to investigate more we need to have a base model that help us to reproduce the behaviour

regards

**Comment by anviz-github** [comment]
https://youtu.be/KDEVUT7XQ4g
Thank you！

**Comment by OmniaGit** [comment]
Dear Anviz,
thanks for your reporting, we are able to reproduce the problem, and we fix it with the following commit
https://github.com/OmniaGit/odooplm/commit/d4445b18a7375dfdeb2fdc9371337c152f67d6d9

thanks in advance,
regards
