### ISSUE TITLE
'Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')

### ISSUE THREAD

**Issue by j540** [OmniaGit/odooplm#71]
When saving a solidworks assembly from the OdooPLM client, an intermittent error appears. And the save fails.

'Connection aborted.', error(10054, 'An existing connection was forcibly closed by the remote host')

By checking the OdooPlm 'DB Thread Action' page, this error can be see, and the specific solidworks part that is causing the error can be seen. The error does not constantly appear on the same part. 

OdooPlm v 15.0
Solidworks 2022
OdooPlm Client: OdooPlm_2019_odoov13_16062022_180028.exe

Solidworks Assembly Size: About 100 parts. 

Thank you for any assistance.

**Comment by j540** [comment]
Attached is the output of the DB Thread page. 

<img width="1306" alt="Screen Shot 2022-06-19 at 1 52 51 PM" src="https://user-images.githubusercontent.com/5269048/174469416-02f4792e-ba96-466e-861d-420b70c927c4.png">

**Comment by j540** [comment]
Also, the odoo instance is deployed on odoo.sh

**Comment by j540** [comment]
This is possibly due to rate limiting on the odoo.sh server.

Possibly the issue is that my OdooPLM client is trying to upload every part file, every time I save. I know the expected behavior is for only modified files to be saved. Possibly, the issue comes from the fact that I am keeping the local client versions of my part files saved in an alternative directory, not the PWS directory. Could this be the issue?

Are there any known workarounds for saving large assemblies?

**Comment by j540** [comment]
@OmniaGit , is there an official 'Large Assembly' upload strategy?

**Comment by OmniaGit** [comment]
Dear @j540 

how your assembly is made ?
do you have only standard solidworks part or are you using some slt .. stp file ?

the client application upload the file in a thread way and upload a pull of 4 file per time.
and you can use this option in order to control the number of simultaneous process to use
 
![image](https://user-images.githubusercontent.com/14873448/174979656-bad9d55f-59d0-4652-89e2-0d07a808dc0a.png)

we do not limit the upload dimension of the file in server controller.

a good strategy could be to save the sub assembly and check-in it after the save operation is completed, so the system dose not upload the sub assembly files.

let me know if this let  you solve the problem.

regards,
Matteo

**Comment by OmniaGit** [comment]
> Attached is the output of the DB Thread page.
> 
> <img alt="Screen Shot 2022-06-19 at 1 52 51 PM" width="1306" src="https://user-images.githubusercontent.com/5269048/174469416-02f4792e-ba96-466e-861d-420b70c927c4.png">

from your image it seems that the Motor gasket is the problem . try to unload it in order to understand if the problem is there..

**Comment by j540** [comment]
Thank you very much, for the help. I will try your suggestions.

**Comment by OmniaGit** [comment]
Let  us know if you solve the problem
regards

**Comment by j540** [comment]
Thank you. Checking-In sub assemblies, to prevent them from uploading, worked very well. I was able to get all my parts, and assemblies uploaded. Thank you.

**Comment by OmniaGit** [comment]
Thanks for the feedback
regards
