### ISSUE TITLE
Solid Works gets stuck

### ISSUE THREAD

**Issue by droidosergioh** [OmniaGit/odooplm#83]
When I try so save document file into Odoo, Solid Works gets stuck

![image](https://github.com/user-attachments/assets/f217b7fb-5cdc-4121-b00f-ff74f8a8deef)

Steps to reproduce it:

1. Open solid works (v2021 in my case)
2. Open any .SLDASM or .SLDPRT file
3. Press into "Save to Odoo" Button
4. Solid works gets frozen. Eventually, I need to close it with the Task manager because is totally stuck

Expected behaviour: 
Document file should be uploaded into odoo without problem. Solid Works should work fine.

Desktop:

- OS: Windows 10
- Browser Chrome
- Version: Odoo v17, and Solid Works 2021

**Comment by OmniaGit** [comment]
Dear,
did you make the login to odoo first ?

https://odooplm.omniasolutions.website/login#Login

regards,

**Comment by droidosergioh** [comment]
Hello

Yes, that was the first thing I did and it was able to connect successfully.

Kindest Regards

**Comment by OmniaGit** [comment]
which client version are you using ?

![image](https://github.com/user-attachments/assets/a844bdbc-e9ba-450d-939e-baf6c36c89e5)

also can  you do e test with a file name like test.sldprt

regards.

**Comment by droidosergioh** [comment]
The OdooPlm_03012024_101548

**Comment by OmniaGit** [comment]
please use the latest stable version that you can find at

https://sourceforge.net/projects/openerpplm/files/Client/Stable/OdooPlm_19092024_164558.exe/download

regards,

**Comment by droidosergioh** [comment]
Nice! Thank you. I got to press save, but now it gets stuck here:

![image](https://github.com/user-attachments/assets/086fc6a8-63ba-4eb7-a1f4-8a3b057b3925)


Some documents were uploaded though

**Comment by OmniaGit** [comment]
in order to correctly upload your model you need to fill up document data and product data.
this is made automatically by using the edit Parts command
https://odooplm.omniasolutions.website/login#Edit-Parts
once you have insert the description and the engineering code you are ready for saving your model

![image](https://github.com/user-attachments/assets/6317fdcc-90eb-4f6b-9cdd-82303b871c39)

another way to save the model is to use the advanced saving form.
have a look at this video for more information

https://youtu.be/ZXSIR0Lvwbs

regards

**Comment by OmniaGit** [comment]
I'll close the issue if you still have the problem let me know
regards

**Comment by droidosergioh** [comment]
> I'll close the issue if you still have the problem let me know regards

Sure! Thank you for the help
